import type { CareerRole } from "./types";

export const CAREER_ROLES: CareerRole[] = [
  {
    id: "ai-engineer",
    name: "AI Engineer",
    category: "AI / ML",
    description: "Designs and deploys AI systems using LLMs, neural nets and ML pipelines.",
    requiredSkills: ["Python", "Machine Learning", "Deep Learning", "TensorFlow", "PyTorch", "APIs", "Data Preprocessing"],
    niceToHave: ["LangChain", "Vector Databases", "Docker"],
  },
  {
    id: "data-scientist",
    name: "Data Scientist",
    category: "Data",
    description: "Extracts insights from data using statistics, ML and visualization.",
    requiredSkills: ["Python", "Statistics", "SQL", "Machine Learning", "Pandas", "Data Visualization", "NumPy"],
    niceToHave: ["R", "Big Data", "A/B Testing"],
  },
  {
    id: "data-analyst",
    name: "Data Analyst",
    category: "Data",
    description: "Turns raw data into reports, dashboards and decisions.",
    requiredSkills: ["SQL", "Excel", "Data Visualization", "Python", "Statistics", "Power BI"],
    niceToHave: ["Tableau", "DAX", "Looker"],
  },
  {
    id: "ml-engineer",
    name: "Machine Learning Engineer",
    category: "AI / ML",
    description: "Builds and deploys ML models in production.",
    requiredSkills: ["Python", "Machine Learning", "MLOps", "Docker", "APIs", "TensorFlow", "Cloud"],
    niceToHave: ["Kubernetes", "Airflow", "Spark"],
  },
  {
    id: "frontend-dev",
    name: "Frontend Web Developer",
    category: "Web",
    description: "Builds user interfaces for the web.",
    requiredSkills: ["HTML", "CSS", "JavaScript", "React", "TypeScript", "APIs", "Git"],
    niceToHave: ["Next.js", "Tailwind CSS", "Testing"],
  },
  {
    id: "fullstack-dev",
    name: "Full Stack Web Developer",
    category: "Web",
    description: "Builds end-to-end web applications.",
    requiredSkills: ["JavaScript", "React", "Node.js", "APIs", "SQL", "MongoDB", "Authentication", "Git"],
    niceToHave: ["TypeScript", "Docker", "Redis"],
  },
  {
    id: "backend-dev",
    name: "Backend Developer",
    category: "Web",
    description: "Designs server-side logic, APIs and databases.",
    requiredSkills: ["Node.js", "Python", "APIs", "SQL", "MongoDB", "Authentication", "Git"],
    niceToHave: ["Microservices", "Redis", "Message Queues"],
  },
  {
    id: "cloud-engineer",
    name: "Cloud Engineer",
    category: "Infra",
    description: "Builds and operates scalable cloud infrastructure.",
    requiredSkills: ["AWS", "Linux", "Networking", "Docker", "Terraform", "Python", "CI/CD"],
    niceToHave: ["Kubernetes", "Azure", "GCP"],
  },
  {
    id: "devops",
    name: "DevOps Engineer",
    category: "Infra",
    description: "Automates build, test and deploy pipelines.",
    requiredSkills: ["Linux", "Docker", "Kubernetes", "CI/CD", "Terraform", "AWS", "Git"],
    niceToHave: ["Ansible", "Prometheus", "Grafana"],
  },
  {
    id: "cybersecurity",
    name: "Cybersecurity Analyst",
    category: "Security",
    description: "Defends systems against threats and vulnerabilities.",
    requiredSkills: ["Networking", "Linux", "Python", "Security Fundamentals", "SIEM", "Cryptography"],
    niceToHave: ["Penetration Testing", "Cloud Security", "Compliance"],
  },
  {
    id: "software-engineer",
    name: "Software Engineer",
    category: "Software",
    description: "General software development across stacks.",
    requiredSkills: ["Data Structures", "Algorithms", "Git", "OOP", "APIs", "Testing", "SQL"],
    niceToHave: ["System Design", "Docker", "Cloud"],
  },
  {
    id: "mobile-dev",
    name: "Mobile App Developer",
    category: "Mobile",
    description: "Builds native or cross-platform mobile apps.",
    requiredSkills: ["React Native", "JavaScript", "APIs", "Git", "UI Design", "State Management"],
    niceToHave: ["Flutter", "Swift", "Kotlin"],
  },
  {
    id: "uiux",
    name: "UI/UX Designer",
    category: "Design",
    description: "Designs intuitive user experiences and interfaces.",
    requiredSkills: ["Figma", "User Research", "Wireframing", "Prototyping", "Design Systems", "Visual Design"],
    niceToHave: ["HTML", "CSS", "Accessibility"],
  },
  {
    id: "product-manager",
    name: "Product Manager",
    category: "Product",
    description: "Defines product vision, strategy and roadmap.",
    requiredSkills: ["Product Strategy", "User Research", "Analytics", "Roadmapping", "Communication", "Agile"],
    niceToHave: ["SQL", "A/B Testing", "Wireframing"],
  },
  {
    id: "business-analyst",
    name: "Business Analyst",
    category: "Business",
    description: "Bridges business needs and technical solutions.",
    requiredSkills: ["SQL", "Excel", "Data Visualization", "Requirements Gathering", "Communication", "Process Modeling"],
    niceToHave: ["Power BI", "Tableau", "Agile"],
  },
];
